-- SQLite
-- DROP TABLE IF EXISTS "ORDERS";
-- DROP TRIGGER IF EXISTS update_total_price_after_insert;

CREATE TABLE IF NOT EXISTS "ORDERS" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ORDER_ID" INTEGER,
    "ITEM_ID" INTEGER,
    "QUANTITY" INTEGER,
    "TOTAL_PRICE" REAL DEFAULT 0,
    "ORDER_DATE" DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY("ITEM_ID") REFERENCES "ITEMS"("ITEM_ID")
);


CREATE TRIGGER IF NOT EXISTS update_total_price_after_insert
AFTER INSERT ON ORDERS
FOR EACH ROW
BEGIN
    -- Update the total price for the new row in ORDERS based on the ITEM_ID and QUANTITY
    UPDATE ORDERS
    SET TOTAL_PRICE = (SELECT PRICE FROM ITEMS WHERE ITEM_ID = NEW.ITEM_ID) * NEW.QUANTITY
    WHERE ORDER_ID = NEW.ORDER_ID;
END;



CREATE TABLE IF NOT EXISTS "ITEMS"(
    "ITEM_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ITEM_NAME" TEXT,
    "PRICE" REAL);

-- INSERT INTO ITEMS (ITEM_NAME, PRICE) VALUES ('Beer', 5.0);
INSERT INTO ITEMS (ITEM_NAME, PRICE) VALUES ('Coke', 2.50);
-- INSERT INTO ORDERS (ITEM_ID, QUANTITY)
-- VALUES (1, 1);
